### ISSUE TITLE
Variable argument list (stdarg.h) function parameter passing does not work correctly

### ISSUE THREAD

**Issue by klaufir216** [khchen/memlib#2]
Memlib mishandles variable argument list function parameter passing (`stdarg.h` in C, `varargs` pragma in nim). Below is an example demonstrating the issue.

The following dll exports a function called `hello` that sums its parameters. The last parameter must end in 0 to signify the end of the variable argument list.

**mydll.c**

```c
#include <stdarg.h>

__declspec(dllexport) int hello(int i, ...);

int hello(int i, ...) {
    int sum = i;
    va_list argp;
    va_start(argp, i);
    
    while(1) {
        int arg_value = va_arg(argp, int);
        sum += arg_value;
        if (arg_value == 0)
            break;
    }
    va_end(argp);
    return sum;
}  
```

Building **mydll.dll**
```
gcc -shared -o mydll.dll mydll.c
```

Using **mydll.dll** from nim:

**main.nim**
```nim
import memlib
import sugar

const StaticDllLib = staticReadDll("mydll.dll")
proc hello_memlib*(i: int): int {.cdecl, varargs, memlib: StaticDllLib, importc: "hello".}
proc hello_dynlib*(i: int): int {.cdecl, varargs, dynlib: "mydll.dll", importc: "hello".}


dump(hello_memlib(1,2,3,4,0))
dump(hello_dynlib(1,2,3,4,0))
```

Produces the following output:

```nim
hello_memlib(1, 2, 3, 4, 0) = 6621520
hello_dynlib(1, 2, 3, 4, 0) = 10
```

The memlib call returns the wrong value indicating some issue with parameter passing in case of variable argument list functions.

Examples attached: [memlib_varargs.zip](https://github.com/khchen/memlib/files/7655013/memlib_varargs.zip)

**Comment by klaufir216** [comment]
One thing that would work for varargs functions is instead of generating something like this

```nim
proc hello*(i: int): int {.gcsafe, raises: [], tags: [], cdecl, varargs.} =
  result = (
    var
      call: (proc (i: int): int {.gcsafe, raises: [], tags: [], cdecl, varargs.})
      sym: LPCSTR
    sym = cstring("hello")
    if isNil(call):
      {.gcsafe.}:
        memlookup(cast[ptr pointer](addr(call)), StaticDllLib, sym)
    call(i))
```

You could generate this:
``` nim
var hello*: (proc (i: int): int {.gcsafe, raises: [], tags: [], cdecl, varargs.})
memlookup(cast[ptr pointer](unsafeAddr(hello)), StaticDllLib, cstring("hello"))
```

Downside is that instead of `memlookup` on first use; with this for `varargs` function the memlookup would happen on import.

**Comment by khchen** [comment]
Thansk, I fixed the issue by using your advise.

**Comment by klaufir216** [comment]
Thanks for all effort, this makes it possible to embed libcurl!
